apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds
  namespace: system
  labels:
    control-plane: ds
    app.kubernetes.io/name: k8slan
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: ds
      app.kubernetes.io/name: k8slan
  template:
    metadata:
      labels:
        control-plane: ds
        app.kubernetes.io/name: k8slan
    spec:
      hostNetwork: true
      initContainers:
      - name: install-cni
        command: ["sh","-c","rm -rf /host/opt/cni/bin/macvtap; cp -f /macvtap-cni /host/opt/cni/bin/macvtap"]
        image: controller:latest
        resources:
          requests:
            cpu: "10m"
            memory: "15Mi"
        securityContext:
          runAsUser: 0
          runAsGroup: 0            
          privileged: true
        volumeMounts:
          - name: cni
            mountPath: /host/opt/cni/bin
            mountPropagation: Bidirectional
      containers:
      - command:
        - /ds
        image: controller:latest
        name: manager
        ports: []
        securityContext:
          runAsUser: 0
          runAsGroup: 0    
          privileged: true 
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: deviceplugin
        - mountPath: /var/run/netns
          name: ns
          mountPropagation: Bidirectional          
      serviceAccountName: ds
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cni
        hostPath:
          path: /opt/cni/bin      
      - hostPath:
          path: /var/lib/kubelet/device-plugins
          type: ""
        name: deviceplugin
      - hostPath:
          path: /root/k8slanns
          type: ""
        name: ns    