---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dset-role
rules:
- apiGroups:
  - lan.k8slan.io
  resources:
  - lans
  verbs:
  - get
  - list
  - update
  - watch
  - patch
